name: Bot04 Docker Image CI

on:
  push:
    paths: [ Bot04/Dockerfile ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Build the Docker image
      run: docker build Bot04
